### ISSUE TITLE
SP-1 attempts

### ISSUE THREAD

**Issue by vitorio** [jpwsutton/instax_api#10]
Hi!  Excited to see this project, and I'm interested in SP-1 support.

Using `sp2.py` as a base, initial communication with an SP-1 is successful if I remove:

```python
printerSpecifications = self.getPrinterSpecifications()
```

and

```python
'specs': printerSpecifications.payload,
```
from `getPrinterInformation()`.

With that, it gets as far as attempting to send the photo to the printer:

```
--- Instax Printer Python Client ---

Connecting to Printer.
Model: SP-1
Firmware: 03.22
Battery State: 4
Prints Remaining: 10
Total Lifetime Prints: 119

Printing Image: /Users/vitorio/Downloads/IMG_20180713_121051175.jpg
Traceback (most recent call last):---------------------------] 40.0% ...About to send Image.                       
  File "/Users/vitorio/Documents/instax-print/.venv/bin/instax-print", line 116, in <module>
    myInstax.printPhoto(encodedImage, printProgress)
  File "/Users/vitorio/Documents/instax-print/.venv/lib/python3.7/site-packages/instax/sp2.py", line 239, in printPhoto
    self.sendSendImageCommand(segment, bytes(segmentBytes))
  File "/Users/vitorio/Documents/instax-print/.venv/lib/python3.7/site-packages/instax/sp2.py", line 143, in sendSendImageCommand
    response = self.sendCommand(cmdPacket)
  File "/Users/vitorio/Documents/instax-print/.venv/lib/python3.7/site-packages/instax/sp2.py", line 80, in sendCommand
    reply = self.send_and_recieve(encodedPacket, 5)
  File "/Users/vitorio/Documents/instax-print/.venv/lib/python3.7/site-packages/instax/sp2.py", line 72, in send_and_recieve
    raise(CommandTimedOutException())
instax.exceptions.CommandTimedOutException
```

According to the log, the "prep command" receives a response; it's the first "Send Image" command that does not.

**Comment by vitorio** [comment]
I've set up an RPi as an access point running `testServer.py`, and the Instax Share app finds it and attempts to connect to it, but it eventually times out.  Is it supposed to record and log traffic like the CLI does?  The logs are always empty.

**Comment by vitorio** [comment]
The SP-1 resolution is 480x640.  Changing the image size (and numbers in `instaxImage.py`) doesn't allow the print to progress any further still.

**Comment by vitorio** [comment]
Updating the image sending code to be more aligned with the lower resolution also doesn't help:

```python
       self.sendPrepImageCommand(16, 0, 921600)
        for segment in range(16):
 ```

Neither does forcing it to keep sending:

```python
    def sendSendImageCommand(self, sequenceNumber, payloadBytes):
        """Send an Image Segment Command."""
        cmdPacket = SendImageCommand(Packet.MESSAGE_MODE_COMMAND,
                                     sequenceNumber=sequenceNumber,
                                     payloadBytes=payloadBytes)
        try:
            response = self.sendCommand(cmdPacket)
        except:
            response = None
        return response
```

That just pushes the communication timeout to the T83 command after.

Suggestions welcome!

**Comment by vitorio** [comment]
@jpwsutton any advice on next steps?  I'll be trying to get this working at a hackathon weekend after next.

**Comment by vitorio** [comment]
In my fork at https://github.com/vitorio/instax_api I have a working simulator, which can impersonate an SP-1 and receive the older format 640x480 JPEG data; and a working client, which can successfully send an older format 640x480 JPEG to the simulator.

The client continues to fail to send to the real SP-1 printer, however.  The error is the same as the one in the opening issue:

```
$ python3 instax-print -v 1 -d -l ../L0020012.JPG 
--- Instax Printer Python Client ---

Connecting to Printer.
Model: SP-1
Firmware: 03.22
Battery State: 4
Prints Remaining: 10
Total Lifetime Prints: 136

Printing Image: ../L0020012.JPG
[------------------------------------------------------------] 0.0% ...Connectin
[======------------------------------------------------------] 10.0% ...Connecte
[============------------------------------------------------] 20.0% ...Locking
[==================------------------------------------------] 30.0% ...Resettin
[========================------------------------------------] 40.0% ...About to
Traceback (most recent call last): 
  File "instax-print", line 118, in <module>
    myInstax.printPhoto(encodedImage, printProgress)
  File "/Users/vitorio/Documents/instax-print/instax_api/instax/sp1.py", line 244, in printPhoto
    resp = self.sendSendImageCommand(segment, bytes(segmentBytes))
  File "/Users/vitorio/Documents/instax-print/instax_api/instax/sp1.py", line 142, in sendSendImageCommand
    response = self.sendCommand(cmdPacket)
  File "/Users/vitorio/Documents/instax-print/instax_api/instax/sp1.py", line 79, in sendCommand
    reply = self.send_and_recieve(encodedPacket, 5)
  File "/Users/vitorio/Documents/instax-print/instax_api/instax/sp1.py", line 71, in send_and_recieve
    raise(CommandTimedOutException())
instax.exceptions.CommandTimedOutException
```

Not sure what's the next debugging step.  Is sniffing with Wireshark my only option?  Is there some sort of comparison I can do with the JSON logs on the server side?

**Comment by cool2man** [comment]
First draft SP1 support which works with my REAL device: https://github.com/jpwsutton/instax_api/compare/master...cool2man:master

The trick was to capture the wifi traffic between the app on a smartphone and the printer. Images are sent as JPEG images, not as RGB data. Changing from RGB (mode 10) to JPEG (mode 2) was the most important fix to get my SP1 working.

**Comment by vitorio** [comment]
I can finally confirm @cool2man's branch works with a real SP-1!  Very exciting, I'm going sort out the differences and merge them into my branch.

**Comment by vitorio** [comment]
In addition to @cool2man's comments about sending JPEG images directly, and changing the mode, other differences appear to be:

- A 153,600 byte file size limit seems to be real
- A 960 byte segment size per send image command seems to be real
- The shading command packet doesn't need to be received by the printer
