### ISSUE TITLE
Stuck when pass image to the printer

### ISSUE THREAD

**Issue by shrewmus** [jpwsutton/instax_api#7]
Hi.

I'll try to use a printer with Kivy application and tinker board.
But sometimes I have an error.

Since this situation repeats, I've decided to create this issue.

Here how it happens:

Power signal via GPIO

InstaxWorks: call to print INSTAX <-- about 1 minute since the printer was powered

[------------------------------------------------------------] 0.0% ...Connecting to instax Printer.           
[======------------------------------------------------------] 10.0% ...Connected! - Sending Pre Print Commands.
[============------------------------------------------------] 20.0% ...Locking Printer for Print.               
[==================------------------------------------------] 30.0% ...Reseting Printer.                         
[========================------------------------------------] 40.0% ...About to send Image.                       
[========================------------------------------------] 40.0% ...Sent image segment 0.         
[=========================-----------------------------------] 41.0% ...Sent image segment 1.         
[=========================-----------------------------------] 42.0% ...Sent image segment 2.         
[==========================----------------------------------] 43.0% ...Sent image segment 3.         
[==========================----------------------------------] 44.0% ...Sent image segment 4.         
[===========================---------------------------------] 45.0% ...Sent image segment 5.         
[============================--------------------------------] 46.0% ...Sent image segment 6.         
[============================--------------------------------] 47.0% ...Sent image segment 7.         
[=============================-------------------------------] 48.0% ...Sent image segment 8.   

And stuck here for some time and then print to the stdout:

[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "fotomat.py", line 241, in <module>
     PhotoApp().run()
   File "/home/linaro/.local/lib/python3.5/site-packages/kivy/app.py", line 826, in run
     runTouchApp()
   File "/home/linaro/.local/lib/python3.5/site-packages/kivy/base.py", line 502, in runTouchApp
     EventLoop.window.mainloop()
   File "/home/linaro/.local/lib/python3.5/site-packages/kivy/core/window/window_sdl2.py", line 727, in mainloop
     self._mainloop()
   File "/home/linaro/.local/lib/python3.5/site-packages/kivy/core/window/window_sdl2.py", line 460, in _mainloop
     EventLoop.idle()
   File "/home/linaro/.local/lib/python3.5/site-packages/kivy/base.py", line 337, in idle
     Clock.tick()
   File "/home/linaro/.local/lib/python3.5/site-packages/kivy/clock.py", line 581, in tick
     self._process_events()
   File "kivy/_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "fotomat.py", line 228, in <lambda>                                              <--- here Clock lambda with timeout about 5 minutes
     Clock.schedule_once(lambda *args: self.instaxClass.print_image(self.run_print_finish), 1)
   File "fotomat.py", line 120, in print_image
     instax_instance.printPhoto(encoded_image)
   File "/home/linaro/.local/lib/python3.5/site-packages/instax/sp2.py", line 252, in printPhoto
     self.sendSendImageCommand(segment, bytes(segmentBytes))
   File "/home/linaro/.local/lib/python3.5/site-packages/instax/sp2.py", line 156, in sendSendImageCommand
     response = self.sendCommand(cmdPacket)
   File "/home/linaro/.local/lib/python3.5/site-packages/instax/sp2.py", line 92, in sendCommand
     reply = self.send_and_recieve(encodedPacket, 120)    <-- here I try to increase timeout from 5 to 120, but it doesn't help
   File "/home/linaro/.local/lib/python3.5/site-packages/instax/sp2.py", line 79, in send_and_recieve
     raise(ConnectError(reply.data))
 instax.exceptions.ConnectError: timed out

 This error is not fired every time, but very frequently - about three times from five. I can't recognize any system in error occurring cases.

A printer is still online. I can ping them. 
Wifi settings in the system use wpa_supplicant.config 
network={
   ssid="INSTAX-"
   key_mgmt=NONE
}
with current printer wifi ssid

**Comment by bserem** [comment]
Can you print from the terminal of the TinkerBoard directly, instead of using Kivy? Does it work?

**Comment by shrewmus** [comment]
I have seen such behavior not each time. But it occurs.
My experiment was so: send power, wait until I can see printers wifi SSID and wait until ping to the printer was successful. Then wait about 20-40 seconds and send call instax-print command from the terminal.
Most of the cases were ended with such a fail.
Can't figure why it occurs. 
When sending the same image file to the printer after failure (after 30 or more seconds after the failure) it receives without stack and prints this file.
Still in investigating this issue.
